version: "3"

services:
  db:
    image: "postgres:latest"
    env_file: .env
  web:
    build: .
    command: make start.docker
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
